/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './index.html',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    extend: {
      colors: {
        // Stitch Design System — ArenaFlow Stadium OS
        "on-surface-variant": "#3e4a41",
        "inverse-primary": "#70db9d",
        "on-primary-container": "#fdfff9",
        "inverse-on-surface": "#f0f0f2",
        "secondary-fixed-dim": "#e9c349",
        "background": "#f9f9fb",
        "tertiary": "#9d3d43",
        "on-surface": "#1a1c1d",
        "on-primary-fixed": "#002110",
        "primary-fixed": "#8df8b7",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#80272e",
        "secondary": "#735c00",
        "secondary-container": "#fed65b",
        "surface-container-high": "#e8e8ea",
        "tertiary-fixed": "#ffdad9",
        "surface-container": "#eeeef0",
        "on-secondary-fixed": "#241a00",
        "on-secondary-container": "#745c00",
        "on-tertiary-fixed": "#40000a",
        "error": "#ba1a1a",
        "tertiary-container": "#bd555a",
        "surface-container-lowest": "#ffffff",
        "pearl": "#FAFAFB",
        "titanium-white": "#F5F5F7",
        "critical-red": "#E03131",
        "on-tertiary-container": "#fffeff",
        "on-primary": "#ffffff",
        "primary": "#006b3f",
        "primary-fixed-dim": "#70db9d",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3f5",
        "graphite": "#1D1D1F",
        "outline-variant": "#bdcabe",
        "surface": "#f9f9fb",
        "surface-variant": "#e2e2e4",
        "surface-dim": "#d9dadc",
        "surface-tint": "#006d40",
        "outline": "#6e7a70",
        "warning-amber": "#FFBF00",
        "surface-container-highest": "#e2e2e4",
        "on-secondary-fixed-variant": "#574500",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#00522f",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3132",
        "surface-bright": "#f9f9fb",
        "primary-container": "#008751",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb3b3",
        "on-background": "#1a1c1d",
        "secondary-fixed": "#ffe088",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "container-padding": "40px",
        "section-margin": "64px",
        "card-gap": "24px",
        "base": "8px",
        "gutter": "24px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "stats-numeric": ["JetBrains Mono", "monospace"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "title-md": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "stats-numeric": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
